version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: nayyer
      DB_PASSWORD: test123
      DB_DATABASE: restapitest123
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://api:3001
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: restapitest123
      MYSQL_USER: nayyer
      MYSQL_PASSWORD: test123
